backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "static"
public_folder: "/"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Título", name: "title", widget: "string", required: true}
      - {label: "Categoría", name: "category", widget: "string", required: true}
      - {label: "Fecha", name: "date", widget: "datetime", required: true}
      - {label: "Imagen", name: "thumbnail", widget: "image", required: true}
      - {label: "Texto", name: "body", widget: "markdown", required: true}