backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "static"
public_folder: "/"

collections:
  - name: "2021" # Used in routes, e.g., /admin/collections/blog
    label: "Posts de Maca (2021)" # Used in the UI
    folder: "content/posts/2021" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Categoría", name: "category", widget: "string", required: true}
      - {label: "Fecha", name: "date", widget: "datetime", required: true}
      - {label: "Imagen", name: "image", widget: "image", required: true}
      - {label: "Texto", name: "body", widget: "markdown", required: true}
      
  - name: "2020" # Used in routes, e.g., /admin/collections/blog
    label: "Posts de Maca (2020)" # Used in the UI
    folder: "content/posts/2020" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Categoría", name: "category", widget: "string", required: true}
      - {label: "Fecha", name: "date", widget: "datetime", required: true}
      - {label: "Imagen", name: "image", widget: "image", required: true}
      - {label: "Texto", name: "body", widget: "markdown", required: true} 

  - name: "2019" # Used in routes, e.g., /admin/collections/blog
    label: "Posts de Maca (2019)" # Used in the UI
    folder: "content/posts/2019" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Categoría", name: "category", widget: "string", required: true}
      - {label: "Fecha", name: "date", widget: "datetime", required: true}
      - {label: "Imagen", name: "image", widget: "image", required: true}
      - {label: "Texto", name: "body", widget: "markdown", required: true} 
      
  - name: "2018" # Used in routes, e.g., /admin/collections/blog
    label: "Posts de Maca (2018)" # Used in the UI
    folder: "content/posts/2018" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Categoría", name: "category", widget: "string", required: true}
      - {label: "Fecha", name: "date", widget: "datetime", required: true}
      - {label: "Imagen", name: "image", widget: "image", required: true}
      - {label: "Texto", name: "body", widget: "markdown", required: true}      
      
  - name: "2017" # Used in routes, e.g., /admin/collections/blog
    label: "Posts de Maca (2017)" # Used in the UI
    folder: "content/posts/2017" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Categoría", name: "category", widget: "string", required: true}
      - {label: "Fecha", name: "date", widget: "datetime", required: true}
      - {label: "Imagen", name: "image", widget: "image", required: true}
      - {label: "Texto", name: "body", widget: "markdown", required: true}          
      
  - name: "2016" # Used in routes, e.g., /admin/collections/blog
    label: "Posts de Maca (2016)" # Used in the UI
    folder: "content/posts/2016" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Categoría", name: "category", widget: "string", required: true}
      - {label: "Fecha", name: "date", widget: "datetime", required: true}
      - {label: "Imagen", name: "image", widget: "image", required: true}
      - {label: "Texto", name: "body", widget: "markdown", required: true} 